#include "webcee.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define SERVER_PORT 8080

#ifdef _WIN32
#include <windows.h>
#define sleep_ms(x) Sleep(x)
#else
#include <unistd.h>
#define sleep_ms(x) usleep((x)*1000)
#endif

// Include the generated UI code
// In a real build, this would be compiled separately and linked.
// For this demo, we assume wce_ui_main is available.
extern void wce_ui_main(void);

// Data model
static char username[64] = "admin";
static char email[64] = "admin@example.com";
static int cpu_usage = 15;
static int mem_usage = 256;

void update_metrics() {
    cpu_usage = (cpu_usage + rand() % 10) % 100;
    mem_usage = (mem_usage + rand() % 50) % 1024;
    
    char buf[32];
    sprintf(buf, "%d%%", cpu_usage);
    wce_data_set("cpu_usage", buf);
    
    sprintf(buf, "%dMB", mem_usage);
    wce_data_set("mem_usage", buf);
}

void on_save() {
    const char* u = wce_data_get("username");
    const char* e = wce_data_get("email");
    if (u) strncpy(username, u, 63);
    if (e) strncpy(email, e, 63);
    
    printf("Saving settings: User=%s, Email=%s\n", username, email);
    wce_data_set("status_text", "Saved!");
}

void on_reset() {
    strcpy(username, "admin");
    strcpy(email, "admin@example.com");
    wce_data_set("username", username);
    wce_data_set("email", email);
    wce_data_set("status_text", "Reset to defaults");
}

void on_refresh() {
    update_metrics();
    wce_data_set("status_text", "Metrics Refreshed");
}

int main() {
    printf("Starting WebCee Showcase...\n");
    
    // Initialize WebCee
    if (wce_init(SERVER_PORT) != 0) {
        printf("Failed to init WebCee\n");
        return 1;
    }
    
    // Register callbacks
    wce_register_function("on_save", on_save);
    wce_register_function("on_reset", on_reset);
    wce_register_function("on_refresh", on_refresh);
    
    // Initial data
    wce_data_set("status_text", "Online");
    wce_data_set("username", username);
    wce_data_set("email", email);
    update_metrics();
    
    // Build UI
    // This function is generated by the compiler from ui.wce
    wce_ui_main();
    
    // Start server
    printf("Server running at http://localhost:%d\n", SERVER_PORT);
    if (wce_start() != 0) {
        printf("Failed to start server\n");
        return 1;
    }
    
    // Main loop
    while (1) {
        sleep_ms(1000);
        // Simulate background work
        // update_metrics(); // Uncomment to auto-update
    }
    
    wce_stop();
    return 0;
}
