#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "core/diagnostic.h"
#include "core/lexer.h"
#include "core/parser.h"
#include "core/ast.h"
#include "core/memory_pool.h"
#include "core/codegen.h"

// Simple file reader
char* read_file(const char* path) {
    FILE* f = fopen(path, "rb");
    if (!f) return NULL;
    
    fseek(f, 0, SEEK_END);
    long size = ftell(f);
    fseek(f, 0, SEEK_SET);
    
    char* content = (char*)malloc(size + 1);
    if (content) {
        fread(content, 1, size, f);
        content[size] = '\0';
    }
    fclose(f);
    return content;
}

int main(int argc, char** argv) {
    if (argc < 2) {
        printf("Usage: wce <input.wce> [output.c]\n");
        return 1;
    }
    
    const char* input_path = argv[1];
    const char* output_path = (argc >= 3) ? argv[2] : "webcee_generated.c";
    
    char* source = read_file(input_path);
    if (!source) {
        printf("Error: Could not read file '%s'\n", input_path);
        return 1;
    }
    
    DiagnosticBag* bag = diagnostic_bag_create();
    Lexer* lexer = lexer_create(source, input_path, bag);
    MemoryPool* pool = memory_pool_create(1024 * 1024); // 1MB pool
    Parser* parser = parser_create(lexer, bag, pool);
    
    WceAstNode* ast = parser_parse(parser);
    
    if (diagnostic_has_errors(bag)) {
        diagnostic_print_all(bag);
        return 1;
    }
    
    FILE* out = fopen(output_path, "w");
    if (!out) {
        printf("Error: Could not open output file '%s'\n", output_path);
        return 1;
    }
    
    fprintf(out, "// Generated by WebCee Compiler\n");
    fprintf(out, "#include \"webcee.h\"\n\n");
    fprintf(out, "void wce_ui_main() {\n");
    codegen_generate(ast, out);
    fprintf(out, "}\n");
    
    fclose(out);
    printf("Successfully compiled '%s' to '%s'\n", input_path, output_path);
    
    // Cleanup
    parser_destroy(parser);
    lexer_destroy(lexer);
    diagnostic_bag_destroy(bag);
    memory_pool_destroy(pool);
    free(source);
    
    return 0;
}
